// Generated by scripts/build-requires.mjs from the `## Requires` tables in
// skills/wf/reference/. Do not edit: run `node scripts/build-requires.mjs`.
import type { RequiresEntry } from './readledger.ts'

export const REQUIRES: readonly RequiresEntry[] = [
  {
    "reference": "augment/benchmark.md",
    "stage": "augment:benchmark",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "04-plan-*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "05c-benchmark.md",
        "kind": "artifact",
        "when": "mode:compare",
        "sections": []
      },
      {
        "input": "augment/benchmark/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_story-arc.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "05c-benchmark.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "augment/experiment.md",
    "stage": "augment:experiment",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "04b-instrument.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "augment/experiment/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_story-arc.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "04c-experiment.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "augment/instrument.md",
    "stage": "augment:instrument",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "04-plan-*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "/.ai/observability.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "augment/instrument/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_story-arc.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "04b-instrument.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "augment/profile.md",
    "stage": "augment:profile",
    "rows": [
      {
        "input": "augment/profile/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_story-arc.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "/.ai/profiles/*/01-profile.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "brainstorm.md",
    "stage": "brainstorm",
    "rows": [
      {
        "input": "intake/brainstorm.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/brainstorm/_design.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      }
    ]
  },
  {
    "reference": "close.md",
    "stage": "close",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "artifact",
        "when": "mode:slice",
        "sections": []
      },
      {
        "input": "03-slice-<slice>.md",
        "kind": "artifact",
        "when": "mode:slice",
        "sections": []
      },
      {
        "input": "99-close.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "skip-slice-<slice>.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "design.md",
    "stage": "design",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02b-design.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "brainstorm-board-design.json",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "06-verify-*.md",
        "kind": "artifact",
        "when": "mode:audit",
        "sections": [
          "Accessibility Gate",
          "Performance Gate"
        ]
      },
      {
        "input": "design/_lane.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/_output.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/stage.md",
        "kind": "procedure",
        "when": "mode:stage",
        "sections": []
      },
      {
        "input": "design/contract.md",
        "kind": "procedure",
        "when": "mode:stage",
        "sections": []
      },
      {
        "input": "design/_carried.md",
        "kind": "procedure",
        "when": "mode:stage",
        "sections": []
      },
      {
        "input": "design/_design-context.md",
        "kind": "procedure",
        "when": "mode:stage",
        "sections": []
      },
      {
        "input": "design/audit.md",
        "kind": "procedure",
        "when": "mode:audit",
        "sections": []
      },
      {
        "input": "design/critique.md",
        "kind": "procedure",
        "when": "mode:critique",
        "sections": []
      },
      {
        "input": "02c-craft.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "07-design-audit.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "07-design-critique.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "docs.md",
    "stage": "docs",
    "rows": [
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "mode:workflow",
        "sections": [
          "Documentation Plan"
        ]
      },
      {
        "input": "08-handoff.md",
        "kind": "artifact",
        "when": "mode:workflow",
        "sections": []
      },
      {
        "input": "docs/_artifacts.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "docs/_audit.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "08b-docs-index.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "handoff.md",
    "stage": "handoff",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "always",
        "sections": [
          "Problem Statement",
          "Documentation Plan"
        ]
      },
      {
        "input": "03-slice.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "05-implement-*.md",
        "kind": "artifact",
        "when": "always",
        "sections": [
          "Summary of Changes",
          "Files Changed",
          "Deviations from Plan",
          "Known Risks / Caveats"
        ]
      },
      {
        "input": "06-verify-*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": [
          "Acceptance Criteria Status",
          "Adversarial Tests",
          "Cross-Browser Delta",
          "Friction Notes",
          "Free Exploration Notes"
        ]
      },
      {
        "input": "07-review-*.yaml",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02b-design.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "02c-craft.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": [
          "Mock fidelity inventory"
        ]
      },
      {
        "input": "04b-instrument.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "04c-experiment.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "05c-benchmark.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "_handoff-config.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_ship-plan-readiness.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_pr-ci-handoff.md",
        "kind": "procedure",
        "when": "mode:pr",
        "sections": []
      },
      {
        "input": "handoff/_pr-triage.md",
        "kind": "procedure",
        "when": "mode:pr",
        "sections": []
      },
      {
        "input": "08-handoff.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "implement.md",
    "stage": "implement",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "always",
        "sections": [
          "Acceptance Criteria",
          "Non-Functional Requirements",
          "Edge Cases / Failure Modes",
          "Out of Scope"
        ]
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "03-slice-<slice>.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "04-plan-<slice>.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "04-plan.md",
        "kind": "artifact",
        "when": "mode:change",
        "sections": []
      },
      {
        "input": "01-<mode>.md",
        "kind": "artifact",
        "when": "mode:change",
        "sections": []
      },
      {
        "input": "01-rca.md",
        "kind": "artifact",
        "when": "mode:rca",
        "sections": []
      },
      {
        "input": "02b-design.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "02c-craft.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "04b-instrument.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "04c-experiment.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "05c-benchmark.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "implement/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "implement/_research.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_story-arc.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/_design-context.md",
        "kind": "procedure",
        "when": "mode:ui",
        "sections": []
      },
      {
        "input": "implement/_reviews-mode.md",
        "kind": "procedure",
        "when": "mode:reviews",
        "sections": []
      },
      {
        "input": "07-review-<slice>.md",
        "kind": "artifact",
        "when": "mode:reviews",
        "sections": []
      },
      {
        "input": "07-review-<slice>.yaml",
        "kind": "artifact",
        "when": "mode:reviews",
        "sections": []
      },
      {
        "input": "05-implement-<slice>.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake.md",
    "stage": "intake",
    "rows": [
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/adopt.md",
    "stage": "intake:adopt",
    "rows": [
      {
        "input": "01-adopt.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_change-mode-tail.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_intake-provenance.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/adopt/_artifacts.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "01-adopt.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "04-plan.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "05-implement.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/audit.md",
    "stage": "intake:audit",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-audit.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "07-review.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "07-review-*.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_findings-ledger.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_subagents.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "01-audit.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "07-review.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "07-review-*.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/brainstorm.md",
    "stage": "intake:brainstorm",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-brainstorm.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "brainstorm-board.json",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/brainstorm/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/brainstorm/_talk.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/brainstorm/_design.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "01-brainstorm.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/default.md",
    "stage": "intake:default",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-intake.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_intake-provenance.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/default/_stack-fingerprint.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/default/_questions.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/default/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "01-intake.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/discover.md",
    "stage": "intake:discover",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-discover.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/discover/_research.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "01-discover.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/extend.md",
    "stage": "intake:extend",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "07-review-*.md",
        "kind": "artifact",
        "when": "mode:from-review",
        "sections": [
          "Recommendations",
          "Triage Decisions"
        ]
      },
      {
        "input": "10-retro.md",
        "kind": "artifact",
        "when": "mode:from-retro",
        "sections": [
          "Recommended Improvements",
          "Keep / Change / Drop",
          "Deferred Debt"
        ]
      },
      {
        "input": "03-slice-probe-*.md",
        "kind": "artifact",
        "when": "mode:from-probe",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "mode:general",
        "sections": []
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/_lane.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/extend/_artifacts.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "03-slice-<slice>.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/fix.md",
    "stage": "intake:fix",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-fix.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_change-mode-tail.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_intake-provenance.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/_lane.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/stage.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "01-fix.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "04-plan.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/hotfix.md",
    "stage": "intake:hotfix",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-hotfix.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_change-mode-tail.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_intake-provenance.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/_lane.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/stage.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "01-hotfix.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "04-plan.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/ideate.md",
    "stage": "intake:ideate",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-ideate.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/ideate/_lenses.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/ideate/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "01-ideate.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/investigate.md",
    "stage": "intake:investigate",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-investigate.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/investigate/_research.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/investigate/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "01-investigate.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/rca.md",
    "stage": "intake:rca",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-rca.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_intake-provenance.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/rca/_research.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/rca/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/rca/_view.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "01-rca.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/refactor.md",
    "stage": "intake:refactor",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-refactor.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_change-mode-tail.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_intake-provenance.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/_lane.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/stage.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "01-refactor.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "04-plan.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "intake/update-deps.md",
    "stage": "intake:update-deps",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-update-deps.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_change-mode-tail.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "intake/_intake-provenance.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/_lane.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/stage.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "intake/update-deps/_exec-artifacts.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "01-update-deps.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "04-plan.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "05-implement.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "06-verify.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "observability.md",
    "stage": "observability",
    "rows": [
      {
        "input": "/.ai/ship-plan.md",
        "kind": "artifact",
        "when": "mode:init",
        "sections": []
      },
      {
        "input": "/.ai/observability.md",
        "kind": "artifact",
        "when": "mode:build",
        "sections": []
      },
      {
        "input": "/.ai/observability.md",
        "kind": "artifact",
        "when": "mode:audit",
        "sections": []
      },
      {
        "input": "observability/init.md",
        "kind": "procedure",
        "when": "mode:init",
        "sections": []
      },
      {
        "input": "observability/build.md",
        "kind": "procedure",
        "when": "mode:build",
        "sections": []
      },
      {
        "input": "observability/audit.md",
        "kind": "procedure",
        "when": "mode:audit",
        "sections": []
      },
      {
        "input": "/.ai/observability.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "plan.md",
    "stage": "plan",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "03-slice-<slice>.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "04-plan.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": [
          "Sibling Plans"
        ]
      },
      {
        "input": "02b-design.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "02c-craft.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "design/_lane.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/_design-context.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "runtime-adapters/_ladder.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_fragment-authoring.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_story-arc.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "augment/instrument.md",
        "kind": "procedure",
        "when": "mode:augment",
        "sections": []
      },
      {
        "input": "augment/experiment.md",
        "kind": "procedure",
        "when": "mode:augment",
        "sections": []
      },
      {
        "input": "augment/benchmark.md",
        "kind": "procedure",
        "when": "mode:augment",
        "sections": []
      },
      {
        "input": "04-plan-<slice>.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "04-plan.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "probe.md",
    "stage": "probe",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "01-<mode>.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "03-slice-*.md",
        "kind": "artifact",
        "when": "mode:slug-wide",
        "sections": []
      },
      {
        "input": "probe/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "probe/_target-resolution.md",
        "kind": "procedure",
        "when": "mode:target",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_surface-defects.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "runtime-adapters.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "runtime-adapters/_ladder.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "runtime-adapters/_protocols.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "03-slice-probe-*.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "recap.md",
    "stage": "recap",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "*.explainer.html.fragment",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "90-recap.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "retro.md",
    "stage": "retro",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "01-*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "02b-design.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "02c-craft.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "03-slice*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "04-plan*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "05-implement*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "06-verify*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "07-review*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "07-design-audit.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "07-design-critique.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "design-notes/*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "08-handoff.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "09-ship-run-*.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "09-ship.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "retro/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/record.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "10-retro.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "review.md",
    "stage": "review",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "03-slice-<slice>.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "04-plan-<slice>.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "05-implement-<slice>.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "06-verify-<slice>.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "01-intake.md",
        "kind": "artifact",
        "when": "mode:slug-wide",
        "sections": [
          "Success Criteria"
        ]
      },
      {
        "input": "04-plan-*.md",
        "kind": "artifact",
        "when": "mode:slug-wide",
        "sections": []
      },
      {
        "input": "05-implement-*.md",
        "kind": "artifact",
        "when": "mode:slug-wide",
        "sections": []
      },
      {
        "input": "06-verify-*.md",
        "kind": "artifact",
        "when": "mode:slug-wide",
        "sections": []
      },
      {
        "input": "01-<mode>.md",
        "kind": "artifact",
        "when": "mode:change",
        "sections": []
      },
      {
        "input": "04-plan.md",
        "kind": "artifact",
        "when": "mode:change",
        "sections": []
      },
      {
        "input": "05-implement.md",
        "kind": "artifact",
        "when": "mode:change",
        "sections": []
      },
      {
        "input": "06-verify.md",
        "kind": "artifact",
        "when": "mode:change",
        "sections": []
      },
      {
        "input": "02b-design.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "02c-craft.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "04b-instrument.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "04c-experiment.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "05c-benchmark.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "07-design-audit.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "07-design-critique.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "07-review-<slice>.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "07-review-<slice>.yaml",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "review/_stage.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "review/_context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "review/_select.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "review/_dispatch.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "review/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_findings-ledger.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "07-review-<slice>.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "07-review.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "shape.md",
    "stage": "shape",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "01-intake.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "design/_lane.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/shape.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "02b-design.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "ship-plan.md",
    "stage": "ship-plan",
    "rows": [
      {
        "input": "/.ai/ship-plan.md",
        "kind": "artifact",
        "when": "mode:edit",
        "sections": []
      },
      {
        "input": "/.ai/ship-plan.md",
        "kind": "artifact",
        "when": "mode:build",
        "sections": []
      },
      {
        "input": "/.ai/ship-plan.md",
        "kind": "artifact",
        "when": "mode:audit",
        "sections": []
      },
      {
        "input": "ship-plan/init.md",
        "kind": "procedure",
        "when": "mode:init",
        "sections": []
      },
      {
        "input": "ship-plan/build.md",
        "kind": "procedure",
        "when": "mode:build",
        "sections": []
      },
      {
        "input": "ship-plan/edit.md",
        "kind": "procedure",
        "when": "mode:edit",
        "sections": []
      },
      {
        "input": "ship-plan/audit.md",
        "kind": "procedure",
        "when": "mode:audit",
        "sections": []
      },
      {
        "input": "/.ai/ship-plan.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "ship.md",
    "stage": "ship",
    "rows": [
      {
        "input": "/.ai/ship-plan.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "08-handoff.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "07-review-*.yaml",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "09-ship-run-*.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "_ship-plan-readiness.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "ship/_run-artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "ship/announce.md",
        "kind": "procedure",
        "when": "mode:announce",
        "sections": []
      },
      {
        "input": "ship/rollback.md",
        "kind": "procedure",
        "when": "mode:rollback",
        "sections": []
      },
      {
        "input": "09-ship-run-*.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "simplify.md",
    "stage": "simplify",
    "rows": [
      {
        "input": "04-plan-<slice>.md",
        "kind": "artifact",
        "when": "mode:plan",
        "sections": []
      },
      {
        "input": "simplify/_research.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "simplify/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "_fragment-authoring.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_story-arc.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "01-simplify.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "03-slice-simplify-*.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "slice.md",
    "stage": "slice",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "01-intake.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "02b-design.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "02c-craft.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "design/_lane.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "design/_design-context.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "design/onboard.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "design/polish.md",
        "kind": "procedure",
        "when": "mode:design",
        "sections": []
      },
      {
        "input": "_story-arc.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "03-slice-<slice>.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "03-slice.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "status.md",
    "stage": "status",
    "rows": [
      {
        "input": "/.ai/workflows/INDEX.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "08-handoff.md",
        "kind": "artifact",
        "when": "mode:roster",
        "sections": []
      },
      {
        "input": ".driver-journal.jsonl",
        "kind": "artifact",
        "when": "mode:detail",
        "sections": []
      },
      {
        "input": "cost.jsonl",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "status/_renders.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "status/_deep.md",
        "kind": "procedure",
        "when": "mode:deep",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "mode:advise",
        "sections": []
      },
      {
        "input": "04-plan-*.md",
        "kind": "artifact",
        "when": "mode:advise",
        "sections": []
      },
      {
        "input": "status/_advise.md",
        "kind": "procedure",
        "when": "mode:advise",
        "sections": []
      },
      {
        "input": "_control-file-ownership.md",
        "kind": "procedure",
        "when": "mode:detail",
        "sections": []
      }
    ]
  },
  {
    "reference": "task.md",
    "stage": "task",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "01-task.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "05-implement.md",
        "kind": "artifact",
        "when": "on-resume",
        "sections": []
      },
      {
        "input": "steer.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "intake/_intake-context.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_compressed-slice.md",
        "kind": "procedure",
        "when": "mode:slug",
        "sections": []
      },
      {
        "input": "01-task.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "05-implement.md",
        "kind": "writes",
        "when": "",
        "sections": []
      },
      {
        "input": "06-verify.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  },
  {
    "reference": "verify.md",
    "stage": "verify",
    "rows": [
      {
        "input": "00-index.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "02-shape.md",
        "kind": "artifact",
        "when": "always",
        "sections": [
          "Acceptance Criteria",
          "Non-Functional Requirements",
          "Edge Cases / Failure Modes",
          "Out of Scope"
        ]
      },
      {
        "input": "po-answers.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "03-slice-<slice>.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "04-plan-<slice>.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "05-implement-<slice>.md",
        "kind": "artifact",
        "when": "always",
        "sections": []
      },
      {
        "input": "01-<mode>.md",
        "kind": "artifact",
        "when": "mode:change",
        "sections": []
      },
      {
        "input": "04-plan.md",
        "kind": "artifact",
        "when": "mode:change",
        "sections": []
      },
      {
        "input": "05-implement.md",
        "kind": "artifact",
        "when": "mode:change",
        "sections": []
      },
      {
        "input": "01-rca.md",
        "kind": "artifact",
        "when": "mode:rca",
        "sections": []
      },
      {
        "input": "02b-design.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "02c-craft.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "04b-instrument.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "04c-experiment.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "05c-benchmark.md",
        "kind": "artifact",
        "when": "if-present",
        "sections": []
      },
      {
        "input": "verify/_artifact.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "verify/_sub-agents.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "verify/_deferrals.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_fix-loop.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "runtime-adapters.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "runtime-adapters/_ladder.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "_story-arc.md",
        "kind": "procedure",
        "when": "always",
        "sections": []
      },
      {
        "input": "06-verify-<slice>.md",
        "kind": "writes",
        "when": "",
        "sections": []
      }
    ]
  }
]
